package com.joe.learn.dao;

import java.util.List;

import com.joe.learn.model.IndexLearn;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

public interface IndexLearnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_learn
     *
     * @mbggenerated Tue Nov 03 22:54:03 CST 2015
     */
    @Delete({
        "delete from index_learn",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_learn
     *
     * @mbggenerated Tue Nov 03 22:54:03 CST 2015
     */
    @Insert({
        "insert into index_learn (id, name, ",
        "date, datestr, ",
        "datelong, content)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{date,jdbcType=TIMESTAMP}, #{datestr,jdbcType=VARCHAR}, ",
        "#{datelong,jdbcType=BIGINT}, #{content,jdbcType=LONGVARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=true, resultType=Integer.class)
    int insert(IndexLearn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_learn
     *
     * @mbggenerated Tue Nov 03 22:54:03 CST 2015
     */
    @Select({
        "select",
        "id, name, date, datestr, datelong, content",
        "from index_learn",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="date", property="date", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="datestr", property="datestr", jdbcType=JdbcType.VARCHAR),
        @Result(column="datelong", property="datelong", jdbcType=JdbcType.BIGINT),
        @Result(column="content", property="content", jdbcType=JdbcType.LONGVARCHAR)
    })
    IndexLearn selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_learn
     *
     * @mbggenerated Tue Nov 03 22:54:03 CST 2015
     */
    @Select({
        "select",
        "id, name, date, datestr, datelong, content",
        "from index_learn"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="date", property="date", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="datestr", property="datestr", jdbcType=JdbcType.VARCHAR),
        @Result(column="datelong", property="datelong", jdbcType=JdbcType.BIGINT),
        @Result(column="content", property="content", jdbcType=JdbcType.LONGVARCHAR)
    })
    List<IndexLearn> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table index_learn
     *
     * @mbggenerated Tue Nov 03 22:54:03 CST 2015
     */
    @Update({
        "update index_learn",
        "set name = #{name,jdbcType=VARCHAR},",
          "date = #{date,jdbcType=TIMESTAMP},",
          "datestr = #{datestr,jdbcType=VARCHAR},",
          "datelong = #{datelong,jdbcType=BIGINT},",
          "content = #{content,jdbcType=LONGVARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(IndexLearn record);
}