package com.joe.learn.model;

import java.util.Date;

public class IndexLearn {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_learn.id
     *
     * @mbggenerated Tue Nov 03 22:54:03 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_learn.name
     *
     * @mbggenerated Tue Nov 03 22:54:03 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_learn.date
     *
     * @mbggenerated Tue Nov 03 22:54:03 CST 2015
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_learn.datestr
     *
     * @mbggenerated Tue Nov 03 22:54:03 CST 2015
     */
    private String datestr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_learn.datelong
     *
     * @mbggenerated Tue Nov 03 22:54:03 CST 2015
     */
    private Long datelong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column index_learn.content
     *
     * @mbggenerated Tue Nov 03 22:54:03 CST 2015
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_learn.id
     *
     * @return the value of index_learn.id
     *
     * @mbggenerated Tue Nov 03 22:54:03 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_learn.id
     *
     * @param id the value for index_learn.id
     *
     * @mbggenerated Tue Nov 03 22:54:03 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_learn.name
     *
     * @return the value of index_learn.name
     *
     * @mbggenerated Tue Nov 03 22:54:03 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_learn.name
     *
     * @param name the value for index_learn.name
     *
     * @mbggenerated Tue Nov 03 22:54:03 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_learn.date
     *
     * @return the value of index_learn.date
     *
     * @mbggenerated Tue Nov 03 22:54:03 CST 2015
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_learn.date
     *
     * @param date the value for index_learn.date
     *
     * @mbggenerated Tue Nov 03 22:54:03 CST 2015
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_learn.datestr
     *
     * @return the value of index_learn.datestr
     *
     * @mbggenerated Tue Nov 03 22:54:03 CST 2015
     */
    public String getDatestr() {
        return datestr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_learn.datestr
     *
     * @param datestr the value for index_learn.datestr
     *
     * @mbggenerated Tue Nov 03 22:54:03 CST 2015
     */
    public void setDatestr(String datestr) {
        this.datestr = datestr == null ? null : datestr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_learn.datelong
     *
     * @return the value of index_learn.datelong
     *
     * @mbggenerated Tue Nov 03 22:54:03 CST 2015
     */
    public Long getDatelong() {
        return datelong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_learn.datelong
     *
     * @param datelong the value for index_learn.datelong
     *
     * @mbggenerated Tue Nov 03 22:54:03 CST 2015
     */
    public void setDatelong(Long datelong) {
        this.datelong = datelong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column index_learn.content
     *
     * @return the value of index_learn.content
     *
     * @mbggenerated Tue Nov 03 22:54:03 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column index_learn.content
     *
     * @param content the value for index_learn.content
     *
     * @mbggenerated Tue Nov 03 22:54:03 CST 2015
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}